Repository ImJaeOne/green-deal, pull requests merged in 2025-02, with the labels that each got.

#2 Feat/#1 kakao map
  index.html
  package.json
  pnpm-lock.yaml
  src/components/KakaoMap/KakaoMap.jsx
  src/pages/ProductList.jsx
  src/utils/getUserLocation.js
Labels: ✨ Feature, 👽재원, 😺영진

#10 Shared/#9 디바운싱 유틸 함수 추가
  src/constants/constants.js
  src/utils/debounceInputs.js
Labels: ✨ Feature, 🐸지윤

#12 ✨ Add: 공통 버튼 컴포넌트 생성
  src/components/common/Button.jsx
Labels: ✨ Feature, 🎨 Html&css, 🐣수민

#15 🎨 Style: 버튼 컴포넌트의 크기 스타일에서 높이 속성 제거 #11
  src/components/common/Button.jsx
Labels: 🎨 Html&css, 🐣수민

#16 Feat/#6 map markers
  src/components/KakaoMap/KakaoMap.jsx
  src/pages/ProductList.jsx
Labels: ✨ Feature, 🎨 Html&css, 😺영진

#17 Feat/#4 search section
  src/components/KakaoMap/KakaoMap.jsx
  src/components/productlist/SearchBar.jsx
  src/components/productlist/SearchList.jsx
  src/components/productlist/SearchListItem.jsx
  src/pages/ProductList.jsx
Labels: ✨ Feature, 👽재원

#18 Feat/#3 회원가입/로그인 구현
  public/profile_default.png
  src/App.jsx
  src/api/userAuthService.js
  src/components/auth/UserForm.jsx
  src/components/auth/UserInput.jsx
  src/hooks/useDebouncedValidation.js
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/store/userStore.js
  src/utils/validateUserInputs.js
Labels: ✨ Feature, 🐸지윤

#19 🎨 Style : 비활성화 상태 버튼 스타일 추가 #11
  src/components/common/Button.jsx
Labels: 🎨 Html&css, 🐣수민

#20 Feat/#8 detail page UI 배치 및 더미데이터 맵핑
  src/components/comments/Comments.jsx
  src/pages/ProductDetail.jsx
  src/routes/Router.jsx
Labels: ✨ Feature, 🎨 Html&css, 🦋미경

#31 [REFACTOR] KakaoMap 리팩토링
  src/components/KakaoMap/KakaoMap.jsx
  src/components/KakaoMap/MapProductMarker.jsx
  src/components/KakaoMap/MapProductModal.jsx
  src/components/KakaoMap/MyLocationMarker.jsx
Labels: 🔨 Refactor, 😺영진
