Repository ImJaeOne/green-deal, pull requests merged in 2025-03, with the labels that each got.

#32 Refactor/#25 auth 로직 리팩토링
  src/App.jsx
  src/api/userAuthService.js
  src/components/auth/UserForm.jsx
  src/components/auth/UserInput.jsx
  src/hooks/useDebouncedValidation.js
  src/routes/PrivateRoute.jsx
  src/routes/PublicRoute.jsx
  src/store/userStore.js
  src/utils/validateUserInputs.js
Labels: 🔨 Refactor, 🐸지윤

#38 Refactor/#25 auth 로직 리팩토링
  src/components/auth/UserForm.jsx
  src/store/userStore.js
Labels: 🔨 Refactor

#36 Feat/#14 user profile
  src/api/userInfoService.js
  src/components/mypage/ProfileImage.jsx
  src/components/mypage/ProfileSection.jsx
  src/constants/mypageConstants.js
  src/hooks/useProfileImage.js
  src/hooks/useProfileInfo.js
  src/pages/MyPage.jsx
  src/utils/profileUtils.js
Labels: ✨ Feature, 🔨 Refactor, 🦚수진

#40 [FEAT] #39 CSS 스타일 & dayjs 사용으로 코드수정
  src/components/KakaoMap/KakaoMap.jsx
  src/components/KakaoMap/MapProductModal.jsx
  src/constants/constants.js
Labels: 🎨 Html&css, 😺영진

#42 Feat/#5 물품등록 기능 구현
  src/components/KakaoMap/KakaoMap.jsx
  src/components/common/Button.jsx
  src/components/common/Input.jsx
  src/components/common/Select.jsx
  src/components/common/TextArea.jsx
  src/components/product/ProductForm.jsx
  src/components/product/ProductImageUpload.jsx
  src/components/product/ProductMapModal.jsx
  src/constants/constants.js
  src/constants/productConstants.js
  src/constants/queryKeys.js
  src/hooks/useImageUpload.js
  src/hooks/useKakaoGeocoder.js
  src/hooks/useProduct.js
  src/hooks/useProductForm.js
  src/hooks/useProductMapModal.js
  src/hooks/useProductRegistration.js
  src/pages/ProductRegistration.jsx
  src/service/productService.js
  src/utils/uploadProductImage.js
  src/utils/validateProducts.js
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor, 🐣수민

#46 Feat/#35 소셜 로그인 구현
  public/icon_google.png
  public/icon_kakao.png
  src/api/userAuthService.js
  src/constants/constants.js
  src/pages/SignIn.jsx
Labels: ✨ Feature, 🐸지윤

#44 Feat/#23 layout
  public/Logo.jpeg
  src/api/productService.js
  src/api/userAuthService.js
  src/components/common/UserProfile.jsx
  src/components/layout/Layout.jsx
  src/components/layout/Nav.jsx
  src/components/layout/NavAuthStatus.jsx
  src/components/layout/UserDropDown.jsx
  src/components/product/ProductForm.jsx
  src/constants/queryKeys.js
  src/hooks/useProduct.js
  src/hooks/useUserQuery.js
  src/routes/Router.jsx
Labels: ✨ Feature, 🎨 Html&css, 👽재원

#47 Feat/#28 detail soldout
  src/components/productdetail/ProductDescription.jsx
  src/components/productdetail/ProductHeader.jsx
  src/components/productdetail/ProductInfo.jsx
  src/components/productdetail/SellerInfo.jsx
  src/pages/ProductDetail.jsx
Labels: ✨ Feature, 🦋미경

#49 Feat/#41 wishes
  src/components/comments/CommentForm.jsx
  src/components/comments/CommentList.jsx
  src/components/comments/Comments.jsx
  src/components/productdetail/ProductHeader.jsx
  src/components/productdetail/Wishes.jsx
  src/pages/ProductDetail.jsx
Labels: ✨ Feature, 🦋미경

#60 Feat/#51 request location access
  src/pages/ProductList.jsx
  src/routes/AllowedRoute.jsx
  src/routes/Router.jsx
  src/store/userStore.js
Labels: ✨ Feature, 🎨 Html&css, 😺영진

#56 Feat/#43 물품등록 수정기능
  src/api/productService.js
  src/api/upsertData.js
  src/components/common/Label.jsx
  src/components/product/ProductForm.jsx
  src/components/product/ProductImageUpload.jsx
  src/constants/queryKeys.js
  src/hooks/useProduct.js
  src/hooks/useProductForm.js
  src/hooks/useProductRegistration.js
  src/pages/ProductRegistration.jsx
  src/service/productService.js
Labels: ✨ Feature, 🐣수민

#58 Feat/#37 mypage product management
  src/api/userInfoService.js
  src/components/mypage/MypageProductList.jsx
  src/components/mypage/TabNav.jsx
  src/hooks/useProfileInfo.js
  src/pages/MyPage.jsx
  src/utils/profileUtils.js
Labels: ✨ Feature, 🦚수진

#61 Refactor/#53 detail page 코드 분리 및 수정
  src/api/productService.js
  src/components/productdetail/CommentForm.jsx
  src/components/productdetail/CommentList.jsx
  src/components/productdetail/Comments.jsx
  src/components/productdetail/ProductDescription.jsx
  src/components/productdetail/ProductHeader.jsx
  src/components/productdetail/ProductInfo.jsx
  src/components/productdetail/ProductLocation.jsx
  src/components/productdetail/SellerInfo.jsx
  src/constants/constants.js
  src/hooks/useGeocode.js
  src/hooks/useProduct.js
  src/pages/ProductDetail.jsx
  src/utils/getAddress.js
Labels: 🔨 Refactor, 🦋미경

#67 Feat/#64 Select 및 TextArea 컴포넌트에 className prop 추가 및 스타일 개선 및 리펙토링
  src/components/common/Select.jsx
  src/components/common/TextArea.jsx
  src/components/product/ProductForm.jsx
  src/components/product/ProductImageUpload.jsx
  src/hooks/useProduct.js
  src/hooks/useProductRegistration.js
  src/pages/ProductRegistration.jsx
Labels: 🎨 Html&css, 🐣수민

#71 Style/#65 search section
  src/components/KakaoMap/MapProductModal.jsx
  src/components/productlist/SearchListItem.jsx
Labels: 🎨 Html&css, 😺영진

#66 Feat/#59 mypage refactor
  src/api/productService.js
  src/api/userInfoService.js
  src/api/wishService.js
  src/components/mypage/MypageProductList.jsx
  src/components/mypage/ProfileSection.jsx
  src/hooks/useProduct.js
  src/hooks/useProfileImage.js
  src/hooks/useProfileInfo.js
  src/hooks/useUserQuery.js
  src/hooks/useWishlist.js
  src/pages/MyPage.jsx
  src/utils/profileUtils.js
Labels: 🔨 Refactor, 🦚수진

#69 Refactor/#62 comments
  src/api/commentService.js
  src/components/productdetail/CommentForm.jsx
  src/components/productdetail/CommentList.jsx
  src/components/productdetail/Comments.jsx
  src/constants/queryKeys.js
  src/hooks/useComment.js
  src/pages/ProductDetail.jsx
Labels: 🔨 Refactor, 🦋미경

#75 Feat/#73 로그인 시 사용자 메타이미지 반영
  src/api/userAuthService.js
  src/store/userStore.js
Labels: ✨ Feature, 🐸지윤

#83 Styling/product registeration style
  src/components/common/Label.jsx
  src/components/common/Select.jsx
  src/components/mypage/MypageProductList.jsx
  src/components/product/ProductForm.jsx
  src/components/product/ProductImageUpload.jsx
  src/pages/ProductRegistration.jsx
Labels: 🎨 Html&css, 🐣수민

#80 Styling/mypage
  src/components/mypage/MypageProductList.jsx
  src/components/mypage/TabNav.jsx
  src/pages/MyPage.jsx
Labels: 🎨 Html&css, 🦚수진

#86 🎨 Styling : 디테일 페이지 CSS 수정
  src/components/productdetail/CommentForm.jsx
  src/components/productdetail/CommentList.jsx
  src/components/productdetail/Comments.jsx
  src/components/productdetail/ProductDescription.jsx
  src/components/productdetail/ProductHeader.jsx
  src/components/productdetail/ProductInfo.jsx
  src/components/productdetail/ProductLocation.jsx
  src/components/productdetail/SellerInfo.jsx
  src/components/productdetail/Wishes.jsx
  src/pages/ProductDetail.jsx
Labels: 🎨 Html&css, 🐸지윤

#85 Style/#78 product list page UI
  src/components/common/HighlightText.jsx
  src/components/layout/Nav.jsx
  src/components/layout/NavAuthStatus.jsx
  src/pages/ProductList.jsx
  src/routes/AllowedRoute.jsx
Labels: 🎨 Html&css, 😺영진

#87 Refactor/#70 wishes
  src/api/wishService.js
  src/components/mypage/MypageProductList.jsx
  src/components/productdetail/Wishes.jsx
  src/constants/queryKeys.js
  src/hooks/useWish.js
  src/hooks/useWishlist.js
Labels: 🔨 Refactor, 🦋미경

#89 Styling/product registeration mobile
  src/components/common/Label.jsx
  src/components/common/Select.jsx
  src/components/product/ProductForm.jsx
  src/hooks/useProduct.js
  src/pages/ProductRegistration.jsx
Labels: 🎨 Html&css, 🐞 BugFix, 🐣수민

#97 Dev
  src/components/mypage/MypageProductList.jsx
  src/hooks/useUserQuery.js
  src/pages/MyPage.jsx
Labels: 🌏 Deploy, 🎨 Html&css, 🐞 BugFix

#98 ✨ Update: 마이 페이지 반응형 수정
  src/components/mypage/MypageProductList.jsx
Labels: 🌏 Deploy, 🎨 Html&css

#99 Docs/#94 readme 작성
  README.md
Labels: 📃 Docs, 🐸지윤, 😺영진

#100 Deploy
  README.md
Labels: 🌏 Deploy, 📃 Docs
